# Generated by Django 4.2.29 on 2026-03-07 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_species', models.CharField(max_length=100)),
                ('plant_count', models.IntegerField()),
                ('soil_preparation', models.CharField(choices=[('none', 'No Preparation'), ('basic', 'Basic'), ('enriched', 'Enriched'), ('professional', 'Professional')], max_length=20)),
                ('time_spent', models.FloatField(help_text='Time in hours')),
                ('gps_location', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('initial_image', models.ImageField(upload_to='activities/')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('total_vu', models.FloatField(default=0)),
                ('released_vu', models.FloatField(default=0)),
                ('locked_vu', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
