# Generated by Django 4.2.29 on 2026-03-07 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_checkpoint', models.IntegerField(choices=[(14, 'Day 14'), (30, 'Day 30'), (90, 'Day 90'), (180, 'Day 180')])),
                ('image', models.ImageField(upload_to='maintenance/')),
                ('gps_location', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plant_health', models.BooleanField(default=False)),
                ('vu_released', models.FloatField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='activities.activity')),
            ],
        ),
    ]
